#微信公众号订阅通知
#GET http://localhost:80/applets/sendMsg
#Accept: application/json

#Mybatis测试，分页查询
#GET http://localhost:80/mybatis/selectToPageHelper?pageNum=3&pageSize=10
#Accept: application/json

#文件下载测试
# 注意：filePath中若使用”\“，则在浏览器地址栏中必须转义成”%5C“
GET http://localhost:80/fileupload/download?filePath=/src/main/resources/images/xiongmaoshaoxiang.png&fileName=xmsx.png&inline=true
Accept: application/json

###