# 应用服务 WEB 访问端口  多环境配置，第一行必须是空行或者注释
server:
  port: 8089

spring:
  application:
    name: demo-springboot
  devtools:
    add-properties: true
  datasource: # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC  # 数据库连接地址
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
  redis: # Redis配置
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 100  # 连接池最大连接数
        max-idle: 20  # 连接池中的最大空闲连接
        min-idle: 5  # 连接池中的最小空闲连接
    timeout: 1000  # 连接超时时间（毫秒）
  session: # spring-session使用
    store-type: none
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  #    image:
  #      location: classpath:images/xiongmaoshaoxiang.png
  #      width:
  #      height:
  #      margin: 2
  #      invert: false
  servlet:
    multipart:
      max-file-size: 10MB  # 单个文件上传大小
      max-request-size: 100MB  # 连续上传文件大小

# 自定义配置
demospringboot:
  multiple-env-conf: prod environment
  rootpath: "D:\\SoftwareEngineering\\workspace_idea\\demo-springboot"  # 项目根路径
  fileupload:
    path: "D:\\SoftwareEngineering\\workspace_idea\\demo-springboot\\backup"  # 文件存储路径

# LOG日志配置，打印SQL
logging:
  level:
    com.example.demospringboot.mapper: DEBUG  # 日志级别

mybatis:
  mapper-locations: classpath:mapper/*xml  # 指定Mybatis的Mapper文件
  type-aliases-package: com.example.demospringboot.entity  # 指定Mybatis的实体目录
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名法

# Mybatis分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
