# 应用服务 WEB 访问端口  多环境配置，第一行必须是空行或者注释
server:
  port: 8089
  servlet:
    context-path: /demo-admin-client

spring:
  application:
    name: demo-springboot-admin-client
  #security:
  #  user:
  #    name: admin
  #    password: admin
  thymeleaf: # 引擎模板配置
    cache: false  # 关闭缓存
    mode: HTML  # 去掉htm5严格校验
    prefix: classpath:/templates/**  # 指定thymeleaf模板路径
    encoding: UTF-8  #指定字符集编码
  boot:
    admin:
      client:
        url: http://127.0.0.1:8088/demo-master/sba  # Admin后台监控，向server注册，支持多个，用英文逗号隔开
        username: admin  # 客户端登录用户
        password: admin  # 客户端登录密码
        instance:
          prefer-ip: true  # 使用ip注册进来，默认值是false（也就是说默认情况下url中会使用hostname的值，而不是ip地址）
        #  service-host-type: ip  # 使用ip注册进来，底版本没有这个配置
        enabled: true
        api-path: instances
    #  notify:
    #    mail:
    #      to:   # 收件人邮箱
    #      from:   # 发件人邮箱
  freemarker:
    check-template-location: false  #

# 集成Actuator后台监控
management:
  health:
    mail:
      enabled: false  # 关闭邮件功能
    redis:
      enabled: false  # 关闭Redis监控
  endpoint:
    health:
      show-details: always  # 显示详细信息
    shutdown:
      enabled: true  # 关闭应用，会导致应用停止，是个危险的动作，默认没有开启这个配置，需要POST请求
    logfile:
      external-file: D:/SoftwareEngineering/workspace_idea/demo-springboot/logs_logback/log_demo_admin_client.log
  endpoints:
    web:
      exposure:
        # 使用通配符*，表示匹配所有端点
        exclude: caches  # 排除的端点
        include: info,health,beans,env,shutdown,threaddump  # 包含的端点
      #  include: '*'
      cors:
        allowed-origins: https://www.demoadminclient.com
        allowed-methods: get,post,delete,put
      base-path: /demo-admin-client-actuator  # 自定义配置监控路径
info:
  actuator:
    name: demo-springboot-admin-client
    version: V1.0.1
    auther: Jason Wang
